targets:
  $default:
    builders:
      drift_dev:
        generate_for:
          include:
            - lib/database/*

      freezed:
        generate_for:
          include:
            - lib/models/*
            - lib/state/app_state.dart
